# Generated by Django 4.0.8 on 2023-01-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proposals',
            new_name='Proposal',
        ),
    ]
