# Generated by Django 4.0.8 on 2023-02-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_rename_proposals_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='price',
        ),
        migrations.AddField(
            model_name='proposal',
            name='assigned',
            field=models.CharField(choices=[('Shallin', 'Shallin'), ('Claude', 'Claude')], default='Shallin', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='country',
            field=models.CharField(choices=[('Bangladesh', 'Bangladesh'), ('Bolivia', 'Bolivia'), ('Burundi', 'Burundi'), ('Cambodia', 'Cambodia'), ('Congo (Kinshasa)', 'Congo (Kinshasa)'), ('Dominican Republic', 'Dominican Republic'), ('Ethiopia', 'Ethiopia'), ('Guatemala', 'Guatemala'), ('Haiti', 'Haiti'), ('Indonesia', 'Indonesia'), ('Kenya', 'Kenya'), ('Mozambique', 'Mozambique'), ('Nicaragua', 'Nicaragua'), ('Peru', 'Peru'), ('Philippines', 'Philippines'), ('Rwanda', 'Rwanda'), ('South Sudan', 'South Sudan'), ('Uganda', 'Uganda')], default='Peru', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='donor',
            field=models.CharField(choices=[('USAID', 'USAID'), ('USDOS', 'USDOS'), ('KOICA', 'KOICA')], default='USAID', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='nofo',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Critical', 'Critical')], default='Normal', max_length=200),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('Pre-Color Review', 'Pre-Color Review'), ('Blue Review', 'Blue Review'), ('Pink Review', 'Pink Review'), ('Red Review', 'Red Review'), ('Green Review', 'Green Review'), ('Gold Review', 'Gold Review'), ('White Review', 'White Review')], default='Pre-Color Review', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(default='Blank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.proposal')),
            ],
        ),
    ]
