# Generated by Django 4.0.8 on 2023-02-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_remove_proposal_price_proposal_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='compliance',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
