# Generated by Django 4.0.8 on 2023-02-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_proposal_compliance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='compliance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
