# Generated by Django 4.0.8 on 2023-02-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_alter_proposal_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='word_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
