# Generated by Django 4.0.8 on 2023-02-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_proposal_word_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='compliance',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='word_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
