# Generated by Django 4.0.8 on 2023-02-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_alter_proposal_compliance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='compliance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='word_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
