# Generated by Django 4.0.8 on 2023-03-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_alter_proposal_compliance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='assigned',
            field=models.CharField(choices=[('Shallin', 'Shallin'), ('Claude', 'Claude')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='compliance',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='donor',
            field=models.CharField(choices=[('USAID', 'USAID'), ('USDOS', 'USDOS'), ('KOICA', 'KOICA')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='word_analysis',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
