# Generated by Django 4.2 on 2023-04-11 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "proposals",
            "0011_alter_proposal_assigned_alter_proposal_compliance_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.ImageField(upload_to="titles")),
                ("content", models.ImageField(upload_to="contents")),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proposals.proposal",
                    ),
                ),
            ],
        ),
    ]
