# Generated by Django 4.2 on 2023-04-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0012_complianceimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complianceimages",
            name="content",
            field=models.ImageField(upload_to="contents/"),
        ),
        migrations.AlterField(
            model_name="complianceimages",
            name="title",
            field=models.ImageField(upload_to="titles/"),
        ),
    ]
