# Generated by Django 4.2 on 2023-04-11 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0014_alter_complianceimages_proposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complianceimages",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="proposals.proposal"
            ),
        ),
    ]
