# Generated by Django 4.2 on 2023-04-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0015_alter_complianceimages_proposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bangladesh", "Bangladesh"),
                    ("Bolivia", "Bolivia"),
                    ("Burundi", "Burundi"),
                    ("Cambodia", "Cambodia"),
                    ("Congo (Kinshasa)", "Congo (Kinshasa)"),
                    ("Dominican Republic", "Dominican Republic"),
                    ("Ethiopia", "Ethiopia"),
                    ("Guatemala", "Guatemala"),
                    ("Haiti", "Haiti"),
                    ("Indonesia", "Indonesia"),
                    ("Kenya", "Kenya"),
                    ("Mozambique", "Mozambique"),
                    ("Nicaragua", "Nicaragua"),
                    ("Peru", "Peru"),
                    ("Philippines", "Philippines"),
                    ("Rwanda", "Rwanda"),
                    ("South Sudan", "South Sudan"),
                    ("Uganda", "Uganda"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
