# Generated by Django 4.2 on 2023-04-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0016_alter_proposal_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complianceimages",
            name="content",
            field=models.ImageField(upload_to="proposals/contents/"),
        ),
        migrations.AlterField(
            model_name="complianceimages",
            name="title",
            field=models.ImageField(upload_to="proposals/titles/"),
        ),
    ]
