# Generated by Django 4.2 on 2023-04-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0017_alter_complianceimages_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complianceimages",
            name="content",
            field=models.ImageField(upload_to="."),
        ),
        migrations.AlterField(
            model_name="complianceimages",
            name="title",
            field=models.ImageField(upload_to="."),
        ),
    ]
