# Generated by Django 4.2 on 2023-04-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0018_alter_complianceimages_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceimages",
            name="content_text",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="complianceimages",
            name="title_text",
            field=models.TextField(null=True),
        ),
    ]
