# Generated by Django 4.2 on 2023-04-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0019_complianceimages_content_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="compliance",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="word_analysis",
        ),
    ]
