# Generated by Django 4.2 on 2023-04-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0020_remove_proposal_compliance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceimages",
            name="page_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="complianceimages",
            name="content_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="complianceimages",
            name="title_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
