# Generated by Django 4.2 on 2023-05-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0021_complianceimages_page_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="compliance_sections",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
