# Generated by Django 4.2 on 2023-05-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0022_proposal_compliance_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="proposal_link",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
