# Generated by Django 4.2 on 2023-05-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0023_proposal_proposal_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="proposal_link",
            field=models.CharField(default="", max_length=500),
        ),
    ]
