# Generated by Django 4.2 on 2023-05-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0024_alter_proposal_proposal_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="proposal_link",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
