# Generated by Django 4.2 on 2023-06-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0026_proposal_proposal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complianceimages",
            name="content",
            field=models.ImageField(blank=True, null=True, upload_to="."),
        ),
        migrations.AlterField(
            model_name="complianceimages",
            name="title",
            field=models.ImageField(blank=True, null=True, upload_to="."),
        ),
    ]
