# Generated by Django 4.2 on 2023-06-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0027_alter_complianceimages_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceimages",
            name="priority",
            field=models.CharField(
                choices=[
                    ("white", "white"),
                    ("#F8F8F8", "#F8F8F8"),
                    ("#AEBC37", "#AEBC37"),
                    ("red", "red"),
                ],
                default="white",
                max_length=200,
            ),
        ),
    ]
