# Generated by Django 4.2 on 2023-07-29 17:45

from django.db import migrations, models
import proposals.models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0029_rename_priority_complianceimages_flagged"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="checklist",
            field=models.JSONField(default=proposals.models.jsonfield_default_value),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="assigned",
            field=models.CharField(
                choices=[("Momodu", "Momodu"), ("Claude", "Claude")],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="donor",
            field=models.CharField(
                choices=[
                    ("USAID", "USAID"),
                    ("USDOS", "USDOS"),
                    ("KOICA", "KOICA"),
                    ("Other", "Other"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
