# Generated by Django 4.2 on 2023-07-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0030_proposal_checklist_alter_proposal_assigned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="toc",
            field=models.IntegerField(default=0),
        ),
    ]
