# Generated by Django 4.2 on 2024-01-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0031_proposal_toc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposal",
            old_name="toc",
            new_name="doc_end",
        ),
        migrations.AddField(
            model_name="proposal",
            name="doc_start",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="proposal",
            name="pages_ran",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="proposal",
            name="pages_total",
            field=models.IntegerField(default=0),
        ),
    ]
