# Generated by Django 4.2 on 2024-01-17 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0032_rename_toc_proposal_doc_end_proposal_doc_start_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="pages_total",
        ),
    ]
