# Generated by Django 4.2 on 2024-01-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0033_remove_proposal_pages_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="loading",
            field=models.BooleanField(default=False),
        ),
    ]
