# Generated by Django 4.2 on 2024-01-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0034_proposal_loading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="country",
        ),
        migrations.AlterField(
            model_name="proposal",
            name="assigned",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
    ]
