# Generated by Django 4.2 on 2024-01-23 16:44

from django.db import migrations, models
import proposals.models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0036_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="checklist",
            field=models.JSONField(default=proposals.models.template_default_value),
        ),
    ]
