# Generated by Django 4.2 on 2024-01-30 18:53

from django.db import migrations, models
import proposals.models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0037_alter_template_checklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="loading_checklist",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="checklist",
            field=models.JSONField(default=proposals.models.template_default_value),
        ),
    ]
