# Generated by Django 4.2 on 2024-02-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0038_proposal_loading_checklist_alter_proposal_checklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="title_count",
            field=models.IntegerField(default=0),
        ),
    ]
